version: '3.8'

services:
  gateway:
    build:
      context: ./Gateway
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/go/src/
    networks:
      - goway

  users:
    build:
      context: ./Users
      dockerfile: dockerfile
    ports:
      - "7070:7070"
    volumes:
      - .:/go/src/
    depends_on:
      - gateway
    networks:
      - goway
networks:
  goway:
    driver: bridge

